[package]
name = "sands-of-duat-bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.8"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
