name: Sands of Duat CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r config/requirements-dev.txt
    
    - name: Lint with flake8
      run: |
        flake8 sands_duat/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 sands_duat/ --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
    
    - name: Format check with black
      run: |
        black --check sands_duat/
    
    - name: Type check with mypy
      run: |
        mypy sands_duat/ --ignore-missing-imports
    
    - name: Validate YAML content
      run: |
        python scripts/manage.py validate
    
    - name: Run unit tests
      run: |
        pytest tests/unit/ -v --cov=sands_duat --cov-report=xml
    
    - name: Run integration tests
      run: |
        pytest tests/integration/ -v
    
    - name: Performance regression tests
      run: |
        pytest tests/performance/ -v --benchmark-only
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Build distribution
      run: |
        python -m pip install --upgrade pip build
        python -m build
    
    - name: Create release artifacts
      run: |
        mkdir -p artifacts
        cp dist/* artifacts/
        echo "BUILD_VERSION=$(python -c 'import sands_duat; print(sands_duat.__version__)')" >> $GITHUB_ENV
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sands-duat-${{ env.BUILD_VERSION }}
        path: artifacts/

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run security scan
      uses: pypa/gh-action-pip-audit@v1.0.8
      with:
        inputs: requirements.txt config/requirements-dev.txt